export const ROLES = {
  ADMIN: "admin",
  OPERATOR: "operator",
  FARMER: "farmer",
};

export const PERMISSIONS = {
  VIEW_DASHBOARD: "view_dashboard",
  VIEW_ALERTS: "view_alerts",
  VIEW_STATIONS: "view_stations",
  MANAGE_STATIONS: "manage_stations",
  MANAGE_ZONES: "manage_zones",
  VIEW_CROP_HEALTH: "view_crop_health",
  USE_AI_ANALYSIS: "use_ai_analysis",
  EXPORT_DATA: "export_data",
  IMPORT_SENSOR_DATA: "import_sensor_data",
  MANAGE_ALERTS: "manage_alerts",
  VIEW_REPORTS: "view_reports",
  VIEW_WEATHER: "view_weather",
  MANAGE_USERS: "manage_users",
  MANAGE_RECOMMENDATIONS: "manage_recommendations",
};

export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_ALERTS,
    PERMISSIONS.VIEW_STATIONS,
    PERMISSIONS.MANAGE_STATIONS,
    PERMISSIONS.MANAGE_ZONES,
    PERMISSIONS.VIEW_CROP_HEALTH,
    PERMISSIONS.USE_AI_ANALYSIS,
    PERMISSIONS.EXPORT_DATA,
    PERMISSIONS.IMPORT_SENSOR_DATA,
    PERMISSIONS.MANAGE_ALERTS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_WEATHER,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_RECOMMENDATIONS,
  ],
  [ROLES.OPERATOR]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_ALERTS,
    PERMISSIONS.VIEW_STATIONS,
    PERMISSIONS.MANAGE_STATIONS,
    PERMISSIONS.VIEW_CROP_HEALTH,
    PERMISSIONS.USE_AI_ANALYSIS,
    PERMISSIONS.EXPORT_DATA,
    PERMISSIONS.IMPORT_SENSOR_DATA,
    PERMISSIONS.VIEW_WEATHER,
  ],
  [ROLES.FARMER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_ALERTS,
    PERMISSIONS.VIEW_STATIONS,
    PERMISSIONS.VIEW_CROP_HEALTH,
    PERMISSIONS.USE_AI_ANALYSIS,
    PERMISSIONS.VIEW_WEATHER,
  ],
};

export const getUserRole = (user) => user?.role || ROLES.OPERATOR;
